--AEROLINEAS
insert into Airline (id, name) values (1, 'Ryanair');
insert into Airline (id, name) values (2, 'Vueling');
insert into Airline (id, name) values (3, 'KLM');
insert into Airline (id, name) values (4, 'Iberia');
insert into Airline (id, name) values (5, 'Qatar Airways');
insert into Airline (id, name) values (6, 'Air Canada');
insert into Airline (id, name) values (7, 'Emirates');
insert into Airline (id, name) values (8, 'TAP Portugal');
insert into Airline (id, name) values (9, 'AirEuropa');
insert into Airline (id, name) values (10, 'EasyJet');
--AEROPUERTOS
insert into Airport (id, code, name) values (1, 'ALC', 'El Altet Airport');
insert into Airport (id, code, name) values (2, 'BCN', 'El Prat Airport');
insert into Airport (id, code, name) values (3, 'MAD', 'Barajar Airport');
insert into Airport (id, code, name) values (4, 'IBZ', 'Ibiza Airport');
insert into Airport (id, code, name) values (5, 'AGP', 'Malaga Airport');
insert into Airport (id, code, name) values (6, 'LHR', 'Heathrow Airport');
insert into Airport (id, code, name) values (7, 'CDG', 'Charles de Gaulle Airport');
insert into Airport (id, code, name) values (8, 'AMS', 'Amsterdam Airport');
insert into Airport (id, code, name) values (9, 'FRA', 'Frankfurt Airport');
insert into Airport (id, code, name) values (10, 'SIN', 'Singapore Changi Airport');
insert into Airport (id, code, name) values (11, 'SFO', 'San Francisco International Airport');
insert into Airport (id, code, name) values (12, 'YYZ', 'Toronto Pearson Airport');
insert into Airport (id, code, name) values (13, 'MEX', 'Benito Suarez International Airport');
insert into Airport (id, code, name) values (14, 'LGW', 'London Gatwick Airport');
insert into Airport (id, code, name) values (15, 'HND', 'Tokyo Haneda Airport');
insert into Airport (id, code, name) values (16, 'DXB', 'Dubai International Airport');
insert into Airport (id, code, name) values (17, 'BRU', 'Brussels Airport');
insert into Airport (id, code, name) values (18, 'SOF', 'Sofia Airport');
insert into Airport (id, code, name) values (19, 'ORY', 'Paris Orly Airport');
insert into Airport (id, code, name) values (20, 'BER', 'Berlin Brandenburg Airport');
insert into Airport (id, code, name) values (21, 'MUC', 'Munich Airport');
insert into Airport (id, code, name) values (22, 'BUD', 'Budapest Airport');
insert into Airport (id, code, name) values (23, 'DUB', 'Dublin Airport');
insert into Airport (id, code, name) values (24, 'NAP', 'Naples Airport');
insert into Airport (id, code, name) values (25, 'VCE', 'Venice Airport');
insert into Airport (id, code, name) values (26, 'MLA', 'Malta Airport');
insert into Airport (id, code, name) values (27, 'LIS', 'Lisbos Airport');
insert into Airport (id, code, name) values (28, 'OPO', 'Porto Airport');
insert into Airport (id, code, name) values (29, 'ZRH', 'Zurich Airport');
insert into Airport (id, code, name) values (30, 'IST', 'Istanbul Airport');
--ASIENTOS
insert into Seat (id, number, aisle) values (1, 'C72 ', 1);
insert into Seat (id, number, aisle) values (2, 'B22 ', 2);
insert into Seat (id, number, aisle) values (3, 'A32 ', 3);
insert into Seat (id, number, aisle) values (4, 'B82 ', 4);
insert into Seat (id, number, aisle) values (6, 'B52 ', 6);
insert into Seat (id, number, aisle) values (7, 'C02 ', 7);
insert into Seat (id, number, aisle) values (8, 'C52 ', 8);
insert into Seat (id, number, aisle) values (9, 'C32 ', 9);
insert into Seat (id, number, aisle) values (14, 'C82 ', 14);
insert into Seat (id, number, aisle) values (15, 'A92 ', 15);
insert into Seat (id, number, aisle) values (16, 'A72 ', 16);
insert into Seat (id, number, aisle) values (17, 'B32 ', 17);
insert into Seat (id, number, aisle) values (18, 'C92 ', 18);
insert into Seat (id, number, aisle) values (19, 'C42 ', 19);
insert into Seat (id, number, aisle) values (21, 'A22 ', 21);
insert into Seat (id, number, aisle) values (24, 'B42 ', 24);
insert into Seat (id, number, aisle) values (25, 'C22 ', 25);

--VUELOS
insert into Flight (id, FLIGHT_NUMBER, DEPARTURE_DATE, ARRIVAL_DATE, DEPARTURE_TIME, ARRIVAL_TIME, DURATION, PRICE, AIRLINE_ID, AIRPORT_ARRIVAL_ID, AIRPORT_DEPARTURE_ID) values (1, 'SV4586', '2021-10-02 15:58:53', '2021-01-29 10:41:00', '21:35', '12:40', 41, 648.85, 9, 5, 20);
insert into Flight (id, FLIGHT_NUMBER, DEPARTURE_DATE, ARRIVAL_DATE, DEPARTURE_TIME, ARRIVAL_TIME, DURATION, PRICE, AIRLINE_ID, AIRPORT_ARRIVAL_ID, AIRPORT_DEPARTURE_ID) values (2, 'FC2543', '2021-06-02 07:06:21', '2021-02-08 16:21:49', '19:17', '5:35', 176, 634.20, 2, 20, 5);
--PASAJEROS
--NO HAY JEJE
--insert into Passenger (id, ID_NUMBER, name, age, email) values (1, '29528428Q', 'bryan', 21, 'bryandf.1996@gmail.com');
insert into Passenger (id, ID_NUMBER, name, age, email, gender, SEAT_ID, FLIGHT_ID) values (1, '46-1074866', 'Chantal', 55, 'cnoen0@mtv.com', 'Male', 14, 2);
insert into Passenger (id, ID_NUMBER, name, age, email, gender, SEAT_ID, FLIGHT_ID) values (2, '77-9820315', 'Kathlin', 73, 'kfanshawe1@soundcloud.com', 'Female', 9, 1);
insert into Passenger (id, ID_NUMBER, name, age, email, gender) values (3, '46-6393577', 'Jessalyn', 6, 'jsmithson2@yale.edu', 'Male');
insert into Passenger (id, ID_NUMBER, name, age, email, gender) values (4, '14-1181817', 'Joletta', 70, 'jdurrell3@comsenz.com', 'Male');
insert into Passenger (id, ID_NUMBER, name, age, email, gender) values (5, '25-0111006', 'Margaretta', 60, 'mmenichino4@merriam-webster.com', 'Male');
insert into Passenger (id, ID_NUMBER, name, age, email, gender) values (6, '16-0483183', 'Worth', 29, 'wsedgman5@amazon.co.jp', 'Male');
insert into Passenger (id, ID_NUMBER, name, age, email, gender) values (7, '25-8359463', 'Karry', 93, 'khaseldine6@wordpress.com', 'Female');
insert into Passenger (id, ID_NUMBER, name, age, email, gender) values (8, '37-2310957', 'Beale', 45, 'byurenev7@bloglines.com', 'Female');
insert into Passenger (id, ID_NUMBER, name, age, email, gender) values (9, '42-1788573', 'Constantin', 7, 'ccambridge8@nba.com', 'Male');
insert into Passenger (id, ID_NUMBER, name, age, email, gender) values (10, '39-8913977', 'Tony', 15, 'tdybell9@nyu.edu', 'Male');
insert into Passenger (id, ID_NUMBER, name, age, email, gender) values (11, '24-9816128', 'Lissa', 48, 'lbengtsona@tinyurl.com', 'Female');
insert into Passenger (id, ID_NUMBER, name, age, email, gender) values (12, '49-7739832', 'Geoffrey', 49, 'gjaumetb@issuu.com', 'Male');
insert into Passenger (id, ID_NUMBER, name, age, email, gender) values (13, '47-1563041', 'Fanya', 73, 'fnisbithc@istockphoto.com', 'Male');
insert into Passenger (id, ID_NUMBER, name, age, email, gender) values (14, '74-5570096', 'Lynnell', 88, 'lgregolid@nymag.com', 'Female');
insert into Passenger (id, ID_NUMBER, name, age, email, gender) values (15, '93-7808900', 'Mersey', 68, 'mruggee@independent.co.uk', 'Male');
insert into Passenger (id, ID_NUMBER, name, age, email, gender) values (16, '42-2118061', 'Shalne', 14, 'slongworthf@symantec.com', 'Male');
insert into Passenger (id, ID_NUMBER, name, age, email, gender) values (17, '16-3873082', 'Preston', 9, 'pallchorneg@storify.com', 'Male');
insert into Passenger (id, ID_NUMBER, name, age, email, gender) values (18, '14-6463213', 'Martelle', 82, 'mbiagionih@oaic.gov.au', 'Female');
insert into Passenger (id, ID_NUMBER, name, age, email, gender) values (19, '06-4146061', 'Jude', 67, 'jleani@epa.gov', 'Male');
insert into Passenger (id, ID_NUMBER, name, age, email, gender) values (20, '21-8480439', 'Chantal', 100, 'cnannininij@biglobe.ne.jp', 'Male');
insert into Passenger (id, ID_NUMBER, name, age, email, gender) values (21, '48-9622075', 'Giff', 39, 'gmaggillandreisk@cmu.edu', 'Female');
insert into Passenger (id, ID_NUMBER, name, age, email, gender) values (22, '63-8791083', 'Sukey', 12, 'stenwickl@ebay.co.uk', 'Male');
insert into Passenger (id, ID_NUMBER, name, age, email, gender) values (23, '23-2740933', 'Thornton', 59, 'tlimbrickm@printfriendly.com', 'Male');
insert into Passenger (id, ID_NUMBER, name, age, email, gender) values (24, '22-2503418', 'Mellicent', 38, 'mbattlesonn@elegantthemes.com', 'Male');
insert into Passenger (id, ID_NUMBER, name, age, email, gender) values (25, '73-7696005', 'Piggy', 18, 'pfawdryo@mapy.cz', 'Female');
insert into Passenger (id, ID_NUMBER, name, age, email, gender) values (26, '60-7790836', 'Hartley', 30, 'hclowleyp@chicagotribune.com', 'Male');
insert into Passenger (id, ID_NUMBER, name, age, email, gender) values (27, '39-3481017', 'Tatiania', 24, 'tkingsburyq@spotify.com', 'Male');
insert into Passenger (id, ID_NUMBER, name, age, email, gender) values (28, '73-2901753', 'Ashley', 84, 'agillerr@shop-pro.jp', 'Male');
insert into Passenger (id, ID_NUMBER, name, age, email, gender) values (29, '17-0102455', 'Christin', 35, 'ckimmels@sfgate.com', 'Female');
insert into Passenger (id, ID_NUMBER, name, age, email, gender) values (30, '86-1518454', 'Ferdy', 18, 'fbrandlit@360.cn', 'Male');
insert into Passenger (id, ID_NUMBER, name, age, email, gender) values (31, '96-7719924', 'Lanie', 56, 'loleksiaku@surveymonkey.com', 'Female');
insert into Passenger (id, ID_NUMBER, name, age, email, gender) values (32, '15-2557191', 'Lissi', 46, 'lmatyjav@umich.edu', 'Male');
insert into Passenger (id, ID_NUMBER, name, age, email, gender) values (33, '23-2171856', 'Hadria', 76, 'hnormandw@ameblo.jp', 'Female');
insert into Passenger (id, ID_NUMBER, name, age, email, gender) values (34, '72-4929064', 'Lanie', 41, 'ldytex@example.com', 'Male');
insert into Passenger (id, ID_NUMBER, name, age, email, gender) values (35, '25-0825345', 'Tedda', 49, 'tsherony@cpanel.net', 'Male');
insert into Passenger (id, ID_NUMBER, name, age, email, gender) values (36, '79-0237856', 'Milt', 73, 'mdudekz@sciencedaily.com', 'Female');
insert into Passenger (id, ID_NUMBER, name, age, email, gender) values (37, '83-9279802', 'Glyn', 46, 'glyes10@shareasale.com', 'Male');
insert into Passenger (id, ID_NUMBER, name, age, email, gender) values (38, '80-8412536', 'Darb', 47, 'dandrolli11@answers.com', 'Male');
insert into Passenger (id, ID_NUMBER, name, age, email, gender) values (39, '63-1515569', 'Nathanil', 86, 'nbaselio12@cyberchimps.com', 'Male');
insert into Passenger (id, ID_NUMBER, name, age, email, gender) values (40, '32-8468548', 'Templeton', 79, 'tgunthorp13@fema.gov', 'Female');
insert into Passenger (id, ID_NUMBER, name, age, email, gender) values (41, '36-8917030', 'Ninette', 7, 'ndillow14@nps.gov', 'Female');
insert into Passenger (id, ID_NUMBER, name, age, email, gender) values (42, '68-4249670', 'Moises', 3, 'mgallegos15@purevolume.com', 'Male');
insert into Passenger (id, ID_NUMBER, name, age, email, gender) values (43, '32-3945049', 'Anatol', 68, 'astammers16@github.io', 'Male');
insert into Passenger (id, ID_NUMBER, name, age, email, gender) values (44, '62-4109781', 'Corenda', 25, 'ckloster17@networksolutions.com', 'Male');
insert into Passenger (id, ID_NUMBER, name, age, email, gender) values (45, '64-0092221', 'Matilda', 35, 'mdyer18@forbes.com', 'Female');
insert into Passenger (id, ID_NUMBER, name, age, email, gender) values (46, '55-7934663', 'Rubie', 8, 'rblader19@google.com', 'Female');
insert into Passenger (id, ID_NUMBER, name, age, email, gender) values (47, '75-5370101', 'Matthew', 47, 'mspadeck1a@mediafire.com', 'Male');
insert into Passenger (id, ID_NUMBER, name, age, email, gender) values (48, '44-9320573', 'Baxie', 43, 'bmccraine1b@marketwatch.com', 'Female');
insert into Passenger (id, ID_NUMBER, name, age, email, gender) values (49, '49-6813170', 'Sisely', 70, 'spearman1c@unblog.fr', 'Male');
insert into Passenger (id, ID_NUMBER, name, age, email, gender) values (50, '52-4368619', 'Ursula', 58, 'uboynton1d@engadget.com', 'Male');
insert into Passenger (id, ID_NUMBER, name, age, email, gender) values (51, '50-1937561', 'Georgeta', 67, 'gsanchez1e@friendfeed.com', 'Male');
insert into Passenger (id, ID_NUMBER, name, age, email, gender) values (52, '94-4323684', 'Halsy', 10, 'halejandri1f@gnu.org', 'Male');
insert into Passenger (id, ID_NUMBER, name, age, email, gender) values (53, '20-3836238', 'Hagen', 75, 'hfrondt1g@artisteer.com', 'Female');
insert into Passenger (id, ID_NUMBER, name, age, email, gender) values (54, '79-1523407', 'Anstice', 89, 'arudsdale1h@who.int', 'Female');
insert into Passenger (id, ID_NUMBER, name, age, email, gender) values (55, '62-3202965', 'Dorian', 54, 'ddellatorre1i@google.fr', 'Male');
insert into Passenger (id, ID_NUMBER, name, age, email, gender) values (56, '17-6485511', 'Vivia', 69, 'vsillis1j@wordpress.com', 'Female');
insert into Passenger (id, ID_NUMBER, name, age, email, gender) values (57, '87-8001718', 'Eddy', 55, 'epeto1k@g.co', 'Female');
insert into Passenger (id, ID_NUMBER, name, age, email, gender) values (58, '79-5336836', 'Burt', 79, 'bransfield1l@liveinternet.ru', 'Male');
insert into Passenger (id, ID_NUMBER, name, age, email, gender) values (59, '54-4853642', 'Menard', 97, 'mwinchurst1m@addtoany.com', 'Male');
insert into Passenger (id, ID_NUMBER, name, age, email, gender) values (60, '33-9771849', 'Valencia', 79, 'vtetford1n@bbb.org', 'Male');
insert into Passenger (id, ID_NUMBER, name, age, email, gender) values (61, '13-3003033', 'Gillie', 87, 'ghairs1o@networkadvertising.org', 'Male');
insert into Passenger (id, ID_NUMBER, name, age, email, gender) values (62, '33-7777832', 'Lia', 65, 'lreedy1p@tamu.edu', 'Female');
insert into Passenger (id, ID_NUMBER, name, age, email, gender) values (63, '64-0086870', 'Christie', 34, 'ctatlow1q@pagesperso-orange.fr', 'Female');
insert into Passenger (id, ID_NUMBER, name, age, email, gender) values (64, '82-0970409', 'Gearard', 1, 'gpownall1r@state.gov', 'Male');
insert into Passenger (id, ID_NUMBER, name, age, email, gender) values (65, '86-7526328', 'Hilliard', 5, 'hpowdrill1s@examiner.com', 'Female');
insert into Passenger (id, ID_NUMBER, name, age, email, gender) values (66, '48-3404706', 'Mady', 4, 'mevelyn1t@list-manage.com', 'Female');
insert into Passenger (id, ID_NUMBER, name, age, email, gender) values (67, '19-1895617', 'Michal', 78, 'mtreadger1u@i2i.jp', 'Male');
insert into Passenger (id, ID_NUMBER, name, age, email, gender) values (68, '58-2730690', 'Ilysa', 28, 'idunlap1v@devhub.com', 'Male');
insert into Passenger (id, ID_NUMBER, name, age, email, gender) values (69, '01-7607902', 'Ted', 76, 'tcomer1w@gravatar.com', 'Female');
insert into Passenger (id, ID_NUMBER, name, age, email, gender) values (70, '53-9850527', 'Emmerich', 82, 'eblaes1x@ow.ly', 'Male');
insert into Passenger (id, ID_NUMBER, name, age, email, gender) values (71, '44-5467215', 'Dom', 29, 'daloigi1y@slashdot.org', 'Female');
insert into Passenger (id, ID_NUMBER, name, age, email, gender) values (72, '37-1135581', 'Mal', 10, 'mgalier1z@un.org', 'Female');
insert into Passenger (id, ID_NUMBER, name, age, email, gender) values (73, '08-9533093', 'Say', 26, 'swasielewski20@time.com', 'Female');
insert into Passenger (id, ID_NUMBER, name, age, email, gender) values (74, '40-5802323', 'Rikki', 89, 'rmaletratt21@jalbum.net', 'Female');
insert into Passenger (id, ID_NUMBER, name, age, email, gender) values (75, '75-6528757', 'Josie', 89, 'jnunan22@fc2.com', 'Male');
insert into Passenger (id, ID_NUMBER, name, age, email, gender) values (76, '93-3341496', 'Margarette', 12, 'mzorzin23@smugmug.com', 'Male');
insert into Passenger (id, ID_NUMBER, name, age, email, gender) values (77, '97-4582388', 'Casey', 77, 'cwiddowson24@dmoz.org', 'Male');
insert into Passenger (id, ID_NUMBER, name, age, email, gender) values (78, '77-3912064', 'Leena', 62, 'lglanister25@posterous.com', 'Female');
insert into Passenger (id, ID_NUMBER, name, age, email, gender) values (79, '89-5801302', 'Violet', 89, 'vpavia26@prlog.org', 'Male');
insert into Passenger (id, ID_NUMBER, name, age, email, gender) values (80, '09-9876677', 'Francisca', 96, 'fcharrington27@cnbc.com', 'Female');
insert into Passenger (id, ID_NUMBER, name, age, email, gender) values (81, '63-8071280', 'Quinton', 56, 'qlevay28@icio.us', 'Male');
insert into Passenger (id, ID_NUMBER, name, age, email, gender) values (82, '29-0680231', 'Alika', 78, 'aloftin29@huffingtonpost.com', 'Female');
insert into Passenger (id, ID_NUMBER, name, age, email, gender) values (83, '17-8735389', 'Brigitte', 82, 'bkinnach2a@newsvine.com', 'Female');
insert into Passenger (id, ID_NUMBER, name, age, email, gender) values (84, '99-9732285', 'Ondrea', 55, 'obeynke2b@google.co.jp', 'Female');
insert into Passenger (id, ID_NUMBER, name, age, email, gender) values (85, '22-9969617', 'Didi', 7, 'djillis2c@home.pl', 'Male');
insert into Passenger (id, ID_NUMBER, name, age, email, gender) values (86, '09-5508133', 'Franny', 75, 'ffonte2d@google.co.jp', 'Female');
insert into Passenger (id, ID_NUMBER, name, age, email, gender) values (87, '22-7916134', 'Humphrey', 69, 'hbedbrough2e@bbc.co.uk', 'Male');
insert into Passenger (id, ID_NUMBER, name, age, email, gender) values (88, '58-2031158', 'Elva', 56, 'enewark2f@canalblog.com', 'Female');
insert into Passenger (id, ID_NUMBER, name, age, email, gender) values (89, '99-5170795', 'Ham', 80, 'hricard2g@163.com', 'Male');
insert into Passenger (id, ID_NUMBER, name, age, email, gender) values (90, '02-3556537', 'Marcie', 3, 'mgossipin2h@ucoz.com', 'Male');
insert into Passenger (id, ID_NUMBER, name, age, email, gender) values (91, '07-4549792', 'Dud', 5, 'djoska2i@whitehouse.gov', 'Female');
insert into Passenger (id, ID_NUMBER, name, age, email, gender) values (92, '76-4640479', 'Hyacinth', 29, 'hcornehl2j@prnewswire.com', 'Female');
insert into Passenger (id, ID_NUMBER, name, age, email, gender) values (93, '63-4173127', 'Drake', 51, 'dmabley2k@google.nl', 'Female');
insert into Passenger (id, ID_NUMBER, name, age, email, gender) values (94, '46-0505779', 'Marji', 93, 'mtorresi2l@nature.com', 'Male');
insert into Passenger (id, ID_NUMBER, name, age, email, gender) values (95, '86-9038701', 'Elvera', 11, 'eberthod2m@hc360.com', 'Male');
insert into Passenger (id, ID_NUMBER, name, age, email, gender) values (96, '14-2290876', 'Kay', 12, 'kmacneilley2n@mozilla.org', 'Female');
insert into Passenger (id, ID_NUMBER, name, age, email, gender) values (97, '42-5971945', 'Davis', 3, 'dzute2o@baidu.com', 'Female');
insert into Passenger (id, ID_NUMBER, name, age, email, gender) values (98, '02-4865857', 'Alejandra', 3, 'acasburn2p@arizona.edu', 'Male');
insert into Passenger (id, ID_NUMBER, name, age, email, gender) values (99, '62-0897589', 'Page', 56, 'pstaig2q@free.fr', 'Male');
insert into Passenger (id, ID_NUMBER, name, age, email, gender) values (100, '04-5998103', 'Adriana', 59, 'akenlin2r@ehow.com', 'Female');